export const VEHICLE_CATEGORIES = {
  LEVES: "Leves",
  UTILITARIOS: "Utilitários",
  PESADOS_TRANSPORTE: "Pesados - Transporte",
  PESADOS_OPERACAO: "Pesados - Operação",
  EQUIPAMENTOS_ESPECIAIS: "Equipamentos Especiais",
  REBOQUES_ACOPLADOS: "Reboques/Acoplados",
} as const;

export const VEHICLE_TYPE_TO_CATEGORY: Record<string, string> = {
  "VEICULO AUTOMOTOR": VEHICLE_CATEGORIES.LEVES,
  POLO: VEHICLE_CATEGORIES.LEVES,
  MOBI: VEHICLE_CATEGORIES.LEVES,
  STRADA: VEHICLE_CATEGORIES.LEVES,
  CAMINHONETE: VEHICLE_CATEGORIES.UTILITARIOS,
  L200: VEHICLE_CATEGORIES.UTILITARIOS,
  ONIBUS: VEHICLE_CATEGORIES.PESADOS_TRANSPORTE,
  MICRO: VEHICLE_CATEGORIES.PESADOS_TRANSPORTE,
  "CAVALO MECANICO": VEHICLE_CATEGORIES.PESADOS_TRANSPORTE,
  "CAMINHAO TANQUE": VEHICLE_CATEGORIES.PESADOS_TRANSPORTE,
  CAMINHAO: VEHICLE_CATEGORIES.PESADOS_TRANSPORTE,
  "CAMINHAO MUNCK": VEHICLE_CATEGORIES.PESADOS_OPERACAO,
  "CAMINHÃO MUNCK": VEHICLE_CATEGORIES.PESADOS_OPERACAO,
  MUNCK: VEHICLE_CATEGORIES.PESADOS_OPERACAO,
  GUINDASTE: VEHICLE_CATEGORIES.EQUIPAMENTOS_ESPECIAIS,
  "GRUA/GUINDASTE": VEHICLE_CATEGORIES.EQUIPAMENTOS_ESPECIAIS,
  EMPILHADEIRA: VEHICLE_CATEGORIES.EQUIPAMENTOS_ESPECIAIS,
  MAQUINAS: VEHICLE_CATEGORIES.EQUIPAMENTOS_ESPECIAIS,
  "UNIDADE MOVEL": VEHICLE_CATEGORIES.EQUIPAMENTOS_ESPECIAIS,
  "UM MOVEL": VEHICLE_CATEGORIES.EQUIPAMENTOS_ESPECIAIS,
  PRANCHA: VEHICLE_CATEGORIES.REBOQUES_ACOPLADOS,
  "REBOQUE TANQUE": VEHICLE_CATEGORIES.REBOQUES_ACOPLADOS,
  "REBOQUE PRANCHA": VEHICLE_CATEGORIES.REBOQUES_ACOPLADOS,
  "CARRETA REBOQUE": VEHICLE_CATEGORIES.REBOQUES_ACOPLADOS,
  POLIGUINDASTE: VEHICLE_CATEGORIES.REBOQUES_ACOPLADOS,
};

export const INSURANCE_TYPES = {
  FROTA: "Frota",
  VIDA: "Seguro de Vida",
  JUDICIAL: "Seguro Judicial",
  TRABALHISTA: "Seguro Trabalhista",
  OBRAS: "Seguro de Obras",
  CONTRATO: "Seguro Contratual",
} as const;

export const COVERAGE_TYPES = ["Total", "Terceiro", "Básico-Terc-Prox AG"] as const;

export const TENDER_STATUS = {
  RASCUNHO: "Rascunho",
  ABERTO: "Aberto",
  ENCERRADO: "Encerrado",
  FINALIZADO: "Finalizado",
} as const;

export const GROUP_COMPANIES = [
  "PLAMONT ENG.",
  "R&I",
  "PLALOG",
  "RID SERVIÇOS",
  "RID METAL",
  "HIROMI",
  "DLV",
  "SAFRA LEASING",
  "LUMI",
] as const;
